{
 "title": "Covid India",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "basicstats",
     "select": [
      [
       { "params": [ "covidDays" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 7, "y": 0 },
   "content": "<p style=\"text-align:center;color:blue\">\n<font size=\"2\"><i>Updated hotspots for Bangalore, GB Nagar, Agra and Bhopal<i/>  \n<p style=\"text-align:center\">\n<b>\n <font size=\"2\">Click for &nbsp;<font size=\"3\"><a href=\"https://indiafightscovid19.online/d/yikrMvqZk/covid19-testing-stats\" style=\"color:#FF0000;\">TestingStats</a>&nbsp;&nbsp;&nbsp;<a href=\"https://indiafightscovid19.online/d/Apmm6qjWk/states-data?orgId=1\" style=\"color:#FF0000;\">StatesData</a>&nbsp;&nbsp;&nbsp;<a href=\"https://indiafightscovid19.online/d/-AZIK9CWk/hotspot-areas?orgId=1\" style=\"color:#FF0000;\">HotspotAreas</a>&nbsp;<font size=\"2\"></b>\n<br /> <a href=\"https://wa.me/?text=https://indiafightscovid19.online %0A%0AFollow this site for latest corona updates and stay safe !!!\" style=\"color:purple;\">Share this link with people you care for</a>\n<i class=\"fa fa-whatsapp\" style=\"font-size:24px;color:green\"></i>\n  \n "
  },
  {
   "title": "India's Fight with covid19",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "India Covid19 Days",
     "measurement": "basicstats",
     "select": [
      [
       { "params": [ "covidDays" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Lockdown Days",
     "measurement": "basicstats",
     "select": [
      [
       { "params": [ "lockdownDays" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Samples tested so far",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "totalsamplestested" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New Cases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Confirmed",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "homedeltaconfirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "confirmed" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Recovered",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeltarecovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Deaths",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeltadeaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Confirmed",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sconfirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "confirmed" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Active",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sactive" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "confirmed" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Recovered",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "srecovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Deaths",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Case Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "covid_india",
     "query": "SELECT \"dailyactive\"  + \"dailyrecovered\"  + \"dailydeceased\" AS \"Confirmed\", \"dailyrecovered\" AS \"Recovered\", \"dailydeceased\" AS \"Deceased\" FROM \"covid_india\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "dailyconfirmed" ], "type": "field" },
       { "params": [ "Confirmed" ], "type": "alias" }
      ],
      [
       { "params": [ "dailyrecovered" ], "type": "field" },
       { "params": [ "Recovered" ], "type": "alias" }
      ],
      [
       { "params": [ "dailydeceased" ], "type": "field" },
       { "params": [ "Deceased" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Confirmed Curve",
     "measurement": "covid_india",
     "query": "SELECT \"dailyactive\"  + \"dailyrecovered\"  + \"dailydeceased\" AS \"Confirmed\" FROM \"covid_india\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "dailyconfirmed" ], "type": "field" },
       { "params": [ "Active" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Newly Reported [Click on State]",
   "type": "table-old",
   "description": "State Unassigned - MoHFW reports that these cases are being reassigned to states",
   "gridPos": { "h": 15, "w": 6, "x": 10, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "covid_india",
     "query": "SELECT sum(\"homedeltaconfirmed\") AS \"Confirm\", sum(\"homedeltarecovered\") AS \"Recovery\", sum(\"homedeltadeaths\") AS \"Deaths\" FROM \"covid_india\" WHERE (\"state\" != 'Daman and Diu') AND $timeFilter GROUP BY \"state\"",
     "select": [
      [
       { "params": [ "sdeltaconfirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirm" ], "type": "alias" }
      ],
      [
       { "params": [ "sdeltarecovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovery" ], "type": "alias" }
      ],
      [
       { "params": [ "sdeltadeaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "Daman and Diu" }
     ]
    }
   ]
  },
  {
   "title": "Total Cases [Click on State]",
   "type": "table-old",
   "description": "There is no district-wise segregation of patient's data in Delhi Govt's Daily bulletin",
   "gridPos": { "h": 25, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "covid_india",
     "query": "SELECT last(\"sconfirmed\") AS \"Cnfrm\",last(\"sactive\") AS \"Actv\", last(\"srecovered\") AS \"Rcvrd\", last(\"sdeaths\") AS \"Deaths\" FROM \"covid_india\" WHERE (\"state\" != 'Daman and Diu') AND $timeFilter GROUP BY \"state\"",
     "select": [
      [
       { "params": [ "sactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Actv" ], "type": "alias" }
      ],
      [
       { "params": [ "srecovered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rcvrd" ], "type": "alias" }
      ],
      [
       { "params": [ "sdeaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ],
      [
       { "params": [ "sconfirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cnfrm" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "Daman and Diu" }
     ]
    }
   ]
  },
  {
   "title": "Active Cases Trend Per State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sgactiveindicator" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed,  Recovered and Deaths [ Cumulative ]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "covid_india",
     "query": "SELECT cumulative_sum(\"Confirmed\") AS \"Confirmed\" ,cumulative_sum(\"Recovered\") AS \"Recovered\", cumulative_sum(\"Deceased\") AS \"Deaths\" FROM \"covid_india\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "totalconfirmed" ], "type": "field" },
       { "params": [ "Confirmed" ], "type": "alias" }
      ],
      [
       { "params": [ "totalactive" ], "type": "field" },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "totalrecovered" ], "type": "field" },
       { "params": [ "Recovered" ], "type": "alias" }
      ],
      [
       { "params": [ "totaldeceased" ], "type": "field" },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Probable Infection Causes in Reported Cases",
   "type": "bargauge",
   "description": "Infection cause data is not available for most of the patients",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_infectionType",
     "groupBy": [
      { "params": [ "infectionType" ], "type": "tag" }
     ],
     "measurement": "rawtata",
     "select": [
      [
       { "params": [ "totalinfections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Infected Age Groups [Based on available data]",
   "type": "bargauge",
   "description": "Age data is not available for most of the patients",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_age_bracket",
     "groupBy": [
      { "params": [ "age_bracket" ], "type": "tag" }
     ],
     "measurement": "rawtata",
     "select": [
      [
       { "params": [ "age_bracketcount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gender [Based on available data]",
   "type": "grafana-piechart-panel",
   "description": "Gender data is not updated for most of the patients",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 31 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_gender",
     "groupBy": [
      { "params": [ "gender" ], "type": "tag" }
     ],
     "measurement": "rawtata",
     "select": [
      [
       { "params": [ "gendercount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "content": "\n#### About us\n\n**We are a group of volunteers working on this portal intending to help community with near to real-time updates on Covid-19 in India.**\n\n**Our Team - [Gaurav Dutt Sharma](https://www.linkedin.com/in/gaurav-dutt-sharma-b8417365/), Dilip Kumar, Pushp Priya, [R. Uma](https://www.linkedin.com/in/uma-raj-b9428317b), Rajesh Kumar, [Shailendra Digarse](https://www.linkedin.com/in/shailendra-digarse-30332a197), T. Vaishnavi and [Vikky Omkar](https://www.linkedin.com/in/vikky-omkar-6552178b)**\n\nFollow us on [twitter](https://twitter.com/indiafightscov1) [telegram](https://t.me/fightbackcovid19) and [facebook](https://www.facebook.com/Indiafightscovid19online-107020570976370)\n\n\n#### Acknowledgement\n\n**Hotspots related data is collated by indiafightscovid19.online team, browsing through the respective district's local news, health department portals and their Twitter handles.**\n**In Addition, we would like to acknowledge that we are using patients' data published by covid19india.org. Heartfelt thanks to the covid19india.org's team for their efforts in this direction.** \n\n**Used  APIs :** [CROWDSOURCED](https://github.com/covid19india/api)\n\n*Write to us for feedbacks:* \n##### communityhelpcovid19@gmail.com\n\n\n\n\n",
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "sitetraffic" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}