{
 "title": "States Data",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "Select State/UT",
    "query": "SHOW TAG VALUES WITH KEY = \"state\""
   }
  ]
 },
 "panels": [
  {
   "title": "$state: Latest Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "alias": "Samples tested so far",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sampleTestsdone" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "Confirmed",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeltaconfirmed" ], "type": "field" },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "Recovered",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeltarecovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "Death",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeltadeaths" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "$state: Total Cases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Confirmed",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sconfirmed" ], "type": "field" },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "Active",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sactive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "Recovered",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "srecovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "Death",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sdeaths" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": " $state: Daily Trend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sgconfirmed" ], "type": "field" },
       { "params": [ "Confirmed" ], "type": "alias" }
      ],
      [
       { "params": [ "sgrecovered" ], "type": "field" },
       { "params": [ "Recovered" ], "type": "alias" }
      ],
      [
       { "params": [ "sgdeaths" ], "type": "field" },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": " $state: COVID19 Curve",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sgrecovered" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ],
      [
       { "params": [ "sgactiveindicator" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "sgdeaths" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": " Samples tested per Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Test",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sampleTestsdone" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "$state: Total Cases",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "covid_india",
     "query": "SELECT \"district\" AS \"District\", \"ddeltaconfirmed\" AS \"New\", \"dconfirmed\" AS \"Cnfrm\", \"dactive\" AS \"Actv\" FROM \"covid_india\" WHERE (\"state\" =~ /^$state$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ddeltaconfirmed" ], "type": "field" },
       { "params": [ "New" ], "type": "alias" }
      ],
      [
       { "params": [ "dconfirmed" ], "type": "field" },
       { "params": [ "Cnfrm" ], "type": "alias" }
      ],
      [
       { "params": [ "dactive" ], "type": "field" },
       { "params": [ "Actv" ], "type": "alias" }
      ],
      [
       { "params": [ "district" ], "type": "field" },
       { "params": [ "District" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Active vs Recovered vs Deaths",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "measurement": "covid_india",
     "query": "SELECT \"district\" AS \"District\",\"dactive\" AS \"Active\", \"drecovered\" AS \"Rcvrd\", \"ddeaths\" AS \"Deaths\" FROM \"covid_india\" WHERE (\"state\" =~ /^$state$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "dactive" ], "type": "field" },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "drecovered" ], "type": "field" },
       { "params": [ "Rcvrd" ], "type": "alias" }
      ],
      [
       { "params": [ "ddeaths" ], "type": "field" },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "$state: Active VS Recovered VS Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$col",
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "sactive" ], "type": "field" },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "srecovered" ], "type": "field" },
       { "params": [ "Recovered" ], "type": "alias" }
      ],
      [
       { "params": [ "sdeaths" ], "type": "field" },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Zonal Classification of Districts (MoHFW)",
   "type": "table",
   "description": "Source - \n\nhttps://www.thehindu.com/news/resources/article31478595.ece/BINARY/Ltr%20to%20CS%2030%20april.pdf.pdf",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "measurement": "mohfwData",
     "select": [
      [
       { "params": [ "district" ], "type": "field" }
      ],
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Cases per District",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "format": "none",
   "targets": [
    {
     "alias": "$tag_district",
     "groupBy": [
      { "params": [ "district" ], "type": "tag" }
     ],
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "dactive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered Cases per District",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "format": "none",
   "targets": [
    {
     "alias": "$tag_district",
     "groupBy": [
      { "params": [ "district" ], "type": "tag" }
     ],
     "measurement": "covid_india",
     "select": [
      [
       { "params": [ "drecovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  }
 ]
}